baseURL = "https://cronytips.github.io/"
title = "Crony Tips"
canonifyURLs = true

theme = "fuji"
hasCJKLanguage = true
enableEmoji = true
enableRobotsTXT = true
disableKinds = ["taxonomyTerm"]

## Change this two to switch between different language
languageCode = "en"  # For RSS, view https://www.rssboard.org/rss-language-codes
defaultContentLanguage = "en"  # For HTML page, now support: en, zh-hans, zh-hant, ja, nl

summaryLength = 100 # Custom summary length, add <!--more--> in post file to custom split point
paginate = 10

googleAnalytics = "UA-171752567-1" # Set your Google Analytics UA here

[outputs]
  home = ["html", "rss", "json"]

[permalinks]
  post = "/:section/:filename/" # Custom post links, e.g. "/:year/:month/:title/"

[params]
  author = "Crony Akatsuki" # You can also set author in post front matter individually
  subTitle = "Anime, manga, light-novel, games and linux lunatics blog"

  # Use CloudFlare Workers to accelerate the Google Analytics
  # If you are using this please comment the googleAnalytics above
  # Check https://github.com/SukkaW/cloudflare-workers-async-google-analytics for more details
  # googleAnalyticsTid = "UA-000000000-0"
  # googleAnalyticsRoute = "https://*.*.workers.dev/"

  # Google AdSense
  # The AdSense code will be inserted between the head tags of your site.
  googleAdsense = "ca-pub-9546162568577568"

  # Word counter and read time indicator in post metadata
  showWordCounter = true
  showReadTime = true

  # License at the end of each post
  showLicense = false
  showToc = false

  # Open Graph & Twitter Card variables
  # You can also set description and images in post front matter individually
  description = "A certain lunatics blog about anime, manga, light novels, games and linux"
  images = ["img/og.png"] # This will use the image called og.png in static/img folder

  # Posts shown in homepage
  mainSections = ["post"]

  # Bangumi image chart id
  # bgmImageChart = "000000"

  # License
  license = "GPL 3"
  licenseLink = "https://www.gnu.org/licenses/gpl-3.0.html"

  # Comments
  # utterances, see: https://utteranc.es/
  # utterancesRepo = "*/*"
  # utterancesIssueTerm = "pathname"

  # Disqus, see: https://disqus.com/admin/install/platforms/universalcode/
  disqusShortname = "crony-tips"
  # Also use DisqusJS for accessing from Mainland China, see: https://github.com/SukkaW/DisqusJS
  # If you want to set multiple api key, see theme's README for more details
  # disqusJSApi = "https://*********/"
  # disqusJSApikey = "**********"

  # custom lazyload placeholder
  # 16:9
  lazyPlaceholder = "/assets/lazyload/dsrca_loading_480x270.svg"
  # 32:9
  lazyPlaceholderRow = "/assets/lazyload/dsrca_loading_960x270.svg"
  # 8:9
  lazyPlaceholderCol = "/assets/lazyload/dsrca_loading_480x540.svg"

  # Use Hugo Pipes in Hugo Extended Version to compile SCSS
  # useHugoPipes = true

  # Let images display in full brightness under dark mode
  # disableDarkImage = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # Enable user to embed HTML snippets in Markdown content
  [markup.highlight]
    codeFences = false  # Disable Hugo's code highlighter

  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3

[taxonomies]
  tag = "tags"

[menu]
  [[menu.nav]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "Archives"
    url = "/archives/"
    weight = 2
  [[menu.nav]]
    name = "About"
    url = "/about/"
    weight = 3
  [[menu.nav]]
    name = "Search"
    url = "/search/"
    weight = 4

  [[menu.link]]
    name = "GitHub"
    url = "https://github.com/CroLinuxGamer"
    weight = 1
  [[menu.link]]
    name = "Instagram"
    url = "https://www.instagram.com/cro.otaku/"
    weight = 2
  [[menu.link]]
    name = "reddit"
    url = "https://www.reddit.com/user/CronyAkatskuki"
    weight = 3
  [[menu.link]]
    name = "email"
    url = "mailto:cronyakatskuki@gmail.com"
    weight = 4
  [[menu.link]]
    name = "twitter"
    url = "https://twitter.com/CronyAkatsuki"
    weight = 5
